CREATE TABLE IF NOT EXISTS person
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      varchar(100) NOT NULL UNIQUE,
    age       int CHECK (age > 0)
);

CREATE TABLE IF NOT EXISTS book
(
    id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title     varchar(150) NOT NULL,
    author    varchar(100) NOT NULL,
    year      int CHECK (year >= -1000 AND year <= EXTRACT(YEAR FROM CURRENT_DATE)),
    person_id int REFERENCES person (id) ON DELETE SET NULL ON UPDATE CASCADE,
    borrow_timestamp TIMESTAMP,
    CONSTRAINT unique_title_author UNIQUE (title, author)
);

