INSERT INTO person (name, age)
VALUES ('Aleksei Petrov', 34),
       ('Natalia Ivanova', 28),
       ('Yuri Gagarin', 45),
       ('Svetlana Smirnova', 31),
       ('Vladimir Korolev', 29),
       ('Elena Vesnina', 36),
       ('Dmitri Sokolov', 40),
       ('Irina Belova', 27),
       ('Mikhail Kuznetsov', 38),
       ('Anastasia Morozova', 25),
       ('Oleg Orlov', 32),
       ('Marina Fedorova', 33),
       ('Konstantin Lebedev', 41),
       ('Tatiana Mikhailova', 30),
       ('Sergei Romanov', 37);

INSERT INTO book (person_id, title, author, year)
VALUES (1, 'War and Peace', 'Leo Tolstoy', 1869),
       (2, 'Pride and Prejudice', 'Jane Austen', 1813),
       (3, '1984', 'George Orwell', 1949),
       (4, 'One Hundred Years of Solitude', 'Gabriel Garcia Marquez', 1967),
       (5, 'The Great Gatsby', 'F. Scott Fitzgerald', 1925),
       (6, 'Moby Dick', 'Herman Melville', 1851),
       (7, 'Crime and Punishment', 'Fyodor Dostoevsky', 1866),
       (8, 'To Kill a Mockingbird', 'Harper Lee', 1960),
       (9, 'The Catcher in the Rye', 'J.D. Salinger', 1951),
       (10, 'The Odyssey', 'Homer', -800),
       (11, 'The Divine Comedy', 'Dante Alighieri', 1320),
       (12, 'Madame Bovary', 'Gustave Flaubert', 1857),
       (14, 'In Search of Lost Time', 'Marcel Proust', 1913),
       (15, 'The Brothers Karamazov', 'Fyodor Dostoevsky', 1880),
       (1, 'Brave New World', 'Aldous Huxley', 1932),
       (2, 'Anna Karenina', 'Leo Tolstoy', 1877),
       (3, 'The Iliad', 'Homer', -750),
       (4, 'Don Quixote', 'Miguel de Cervantes', 1605),
       (5, 'The Picture of Dorian Gray', 'Oscar Wilde', 1890),
       (6, 'Ulysses', 'James Joyce', 1922),
       (7, 'Les Misérables', 'Victor Hugo', 1862),
       (8, 'The Grapes of Wrath', 'John Steinbeck', 1939),
       (9, 'The Old Man and the Sea', 'Ernest Hemingway', 1952),
       (10, 'The Count of Monte Cristo', 'Alexandre Dumas', 1844),
       (11, 'Great Expectations', 'Charles Dickens', 1861),
       (12, 'The Sound and the Fury', 'William Faulkner', 1929),
       (13, 'Jane Eyre', 'Charlotte Brontë', 1847),
       (14, 'Wuthering Heights', 'Emily Brontë', 1847),
       (15, 'The Hobbit', 'J.R.R. Tolkien', 1937),
       (1, 'Lolita', 'Vladimir Nabokov', 1955),
       (2, 'A Tale of Two Cities', 'Charles Dickens', 1859);